### PR TITLE
Emit connection events

### PR DESCRIPTION
**Pull request by brandonhamilton**
Supports request from #12

### CODE REVIEW

**Comment by chris-rock** [comment]
@brandonhamilton looks great can we add some event emitter tests?

**Comment by DexterYan** [comment]
Sorry, I didn't see brandonhamilton pull request. You can ignore my pull request. Great Job! Thanks brandonhamilton

**Comment by chris-rock** [comment]
thanks @brandonhamilton

**Comment by chris-rock** [comment]
@DexterYan great, I think it makes sense to stick to one solution.

**Comment by chris-rock** [comment]
published as 0.3.4

**Comment by palmic** [comment]
Thanx!

**Pull request merged**
